package com.appvendor.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFF6B00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC7)
val md_theme_light_onPrimaryContainer = Color(0xFF331100)
val md_theme_light_secondary = Color(0xFF0F172A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE2E8F0)
val md_theme_light_onSecondaryContainer = Color(0xFF0F172A)
val md_theme_light_tertiary = Color(0xFF94A3B8)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF1F5F9)
val md_theme_light_onTertiaryContainer = Color(0xFF334155)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FAFC)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFE2E8F0)
val md_theme_light_onSurfaceVariant = Color(0xFF475569)
val md_theme_light_outline = Color(0xFF94A3B8)
val md_theme_light_inverseOnSurface = Color(0xFFF1F5F9)
val md_theme_light_inverseSurface = Color(0xFF334155)
val md_theme_light_inversePrimary = Color(0xFFFFB68F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFFF6B00)
val md_theme_light_outlineVariant = Color(0xFFCBD5E1)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB68F)
val md_theme_dark_onPrimary = Color(0xFF4D1C00)
val md_theme_dark_primaryContainer = Color(0xFF702D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC7)
val md_theme_dark_secondary = Color(0xFF94A3B8)
val md_theme_dark_onSecondary = Color(0xFF0F172A)
val md_theme_dark_secondaryContainer = Color(0xFF1E293B)
val md_theme_dark_onSecondaryContainer = Color(0xFFE2E8F0)
val md_theme_dark_tertiary = Color(0xFFCBD5E1)
val md_theme_dark_onTertiary = Color(0xFF334155)
val md_theme_dark_tertiaryContainer = Color(0xFF475569)
val md_theme_dark_onTertiaryContainer = Color(0xFFF1F5F9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F172A)
val md_theme_dark_onBackground = Color(0xFFE2E8F0)
val md_theme_dark_surface = Color(0xFF0F172A)
val md_theme_dark_onSurface = Color(0xFFE2E8F0)
val md_theme_dark_surfaceVariant = Color(0xFF334155)
val md_theme_dark_onSurfaceVariant = Color(0xFF94A3B8)
val md_theme_dark_outline = Color(0xFF64748B)
val md_theme_dark_inverseOnSurface = Color(0xFF0F172A)
val md_theme_dark_inverseSurface = Color(0xFFE2E8F0)
val md_theme_dark_inversePrimary = Color(0xFFFF6B00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB68F)
val md_theme_dark_outlineVariant = Color(0xFF475569)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFFF6B00)

// Dashboard Redesign Colors
val DashboardBackground = Color(0xFFF7F8FA)
val CardBackground = Color(0xFFFFFFFF)
val TextPrimary = Color(0xFF1E1E1E)
val TextSecondary = Color(0xFF757575)
val TextTertiary = Color(0xFF9E9E9E)

val MetricBlueBg = Color(0xFFE3F2FD)
val MetricBlueIcon = Color(0xFF1E88E5)
val MetricYellowBg = Color(0xFFFFF3E0)
val MetricYellowIcon = Color(0xFFF4511E)
val MetricPurpleBg = Color(0xFFF3E5F5)
val MetricPurpleIcon = Color(0xFF8E24AA)
val MetricGreenBg = Color(0xFFE8F5E9)
val MetricGreenIcon = Color(0xFF43A047)

val QueueGreenBg = Color(0xFFE8F5E9)
val QueueGreenText = Color(0xFF2E7D32)
val QueueBlueBg = Color(0xFFE3F2FD)
val QueueBlueText = Color(0xFF1565C0)
val QueueOrangeBg = Color(0xFFFFF3E0)
val QueueOrangeText = Color(0xFFEF6C00)

val TrendGreen = Color(0xFF4CAF50)
val TrendRed = Color(0xFFF44336)
